sqltest:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: LAPTOP-AMIVJC0N
      port: 1433
      database: rawim
      schema: dbtcore
      windows_login: True
      trust_cert: True
      
      
